# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_stream(
                '/code_assistance.AgentService/ExecuteTask',
                request_serializer=agent__pb2.UserQuery.SerializeToString,
                response_deserializer=agent__pb2.AgentResponse.FromString,
                )
        self.SyncFile = channel.unary_unary(
                '/code_assistance.AgentService/SyncFile',
                request_serializer=agent__pb2.FileUpdate.SerializeToString,
                response_deserializer=agent__pb2.SyncStatus.FromString,
                )


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agent__pb2.UserQuery.FromString,
                    response_serializer=agent__pb2.AgentResponse.SerializeToString,
            ),
            'SyncFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncFile,
                    request_deserializer=agent__pb2.FileUpdate.FromString,
                    response_serializer=agent__pb2.SyncStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'code_assistance.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/code_assistance.AgentService/ExecuteTask',
            agent__pb2.UserQuery.SerializeToString,
            agent__pb2.AgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/code_assistance.AgentService/SyncFile',
            agent__pb2.FileUpdate.SerializeToString,
            agent__pb2.SyncStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
