# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x0f\x63ode_assistance\"C\n\tUserQuery\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"B\n\rAgentResponse\x12\r\n\x05phase\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x11\n\tcitations\x18\x03 \x03(\t\"D\n\nFileUpdate\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\".\n\nSyncStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa1\x01\n\x0c\x41gentService\x12K\n\x0b\x45xecuteTask\x12\x1a.code_assistance.UserQuery\x1a\x1e.code_assistance.AgentResponse0\x01\x12\x44\n\x08SyncFile\x12\x1b.code_assistance.FileUpdate\x1a\x1b.code_assistance.SyncStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERQUERY']._serialized_start=32
  _globals['_USERQUERY']._serialized_end=99
  _globals['_AGENTRESPONSE']._serialized_start=101
  _globals['_AGENTRESPONSE']._serialized_end=167
  _globals['_FILEUPDATE']._serialized_start=169
  _globals['_FILEUPDATE']._serialized_end=237
  _globals['_SYNCSTATUS']._serialized_start=239
  _globals['_SYNCSTATUS']._serialized_end=285
  _globals['_AGENTSERVICE']._serialized_start=288
  _globals['_AGENTSERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
