// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1G3K7TCrZMQpP37Lv8fGOzqpzBQVPCDI',
    appId: '1:424136555923:web:3cd4aea033d56784debc66',
    messagingSenderId: '424136555923',
    projectId: 'ai-study-assistant-d8ddf',
    authDomain: 'ai-study-assistant-d8ddf.firebaseapp.com',
    storageBucket: 'ai-study-assistant-d8ddf.firebasestorage.app',
    measurementId: 'G-S06KEV7B1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4mZ4xr6pURC459_rBefb_CH3ZC5YVBE',
    appId: '1:424136555923:android:827025bf4cb247ccdebc66',
    messagingSenderId: '424136555923',
    projectId: 'ai-study-assistant-d8ddf',
    storageBucket: 'ai-study-assistant-d8ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCUvJL9Rp5GJ7dgvJ5zxc5618SieT2DBk',
    appId: '1:424136555923:ios:cc00bced8d200745debc66',
    messagingSenderId: '424136555923',
    projectId: 'ai-study-assistant-d8ddf',
    storageBucket: 'ai-study-assistant-d8ddf.firebasestorage.app',
    iosClientId: '424136555923-263j3lufietg838pm09d3b557shl20jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyAssistance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCUvJL9Rp5GJ7dgvJ5zxc5618SieT2DBk',
    appId: '1:424136555923:ios:cc00bced8d200745debc66',
    messagingSenderId: '424136555923',
    projectId: 'ai-study-assistant-d8ddf',
    storageBucket: 'ai-study-assistant-d8ddf.firebasestorage.app',
    iosClientId: '424136555923-263j3lufietg838pm09d3b557shl20jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyAssistance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1G3K7TCrZMQpP37Lv8fGOzqpzBQVPCDI',
    appId: '1:424136555923:web:2d019ac7d1a494c1debc66',
    messagingSenderId: '424136555923',
    projectId: 'ai-study-assistant-d8ddf',
    authDomain: 'ai-study-assistant-d8ddf.firebaseapp.com',
    storageBucket: 'ai-study-assistant-d8ddf.firebasestorage.app',
    measurementId: 'G-NFXTDZEH6J',
  );
}
